[settings]
experimental = true

[tools]
ansible = "11.5.0"
"aqua:aws-cli" = "2.27.11"
"aqua:cockroach" = "25.1.5"
ast-grep = "0.38.2"
azure-cli = "2.72.0"
bat = "0.25.0"
bat-extras = "2024.08.24"
bottom = "0.10.2"
btop = "1.4.2"
buf = "1.53.0"
bun = "1.2.11"
cargo-binstall = "1.12.3"
cargo-insta = "1.43.1"
cargo-make = "0.37.24"
"cargo:aoc-cli" = "0.12.0"
"cargo:arroyo" = "0.7.0"
"cargo:asm-lsp" = "0.10.0"
"cargo:ast-grep" = "0.37.0"
"cargo:bat" = "0.25.0"
"cargo:bootimage" = "0.10.3"
"cargo:bottom" = "0.10.2"
"cargo:cargo-afl" = "0.15.18"
"cargo:cargo-audit" = "0.21.2"
"cargo:cargo-auditable" = "0.6.7"
"cargo:cargo-binstall" = "1.12.4"
"cargo:cargo-binutils" = "0.3.6"
"cargo:cargo-bloat" = "0.12.1"
"cargo:cargo-crev" = "0.26.4"
"cargo:cargo-criterion" = "1.1.0"
"cargo:cargo-debug" = "0.3.0"
"cargo:cargo-deny" = "0.18.2"
"cargo:cargo-dist" = "0.28.0"
"cargo:cargo-docs" = "0.1.34"
"cargo:cargo-edit" = "0.13.3"
"cargo:cargo-expand" = "1.0.106"
"cargo:cargo-fuzz" = "0.12.0"
"cargo:cargo-geiger" = "0.12.0"
"cargo:cargo-insta" = "1.43.1"
"cargo:cargo-license" = "0.6.1"
"cargo:cargo-llvm-lines" = "0.4.42"
"cargo:cargo-machete" = "0.8.0"
"cargo:cargo-make" = "0.37.24"
"cargo:cargo-msrv" = "0.18.4"
"cargo:cargo-mutants" = "25.0.1"
"cargo:cargo-nextest" = "0.9.95"
"cargo:cargo-outdated" = "0.17.0"
"cargo:cargo-public-api" = "0.47.0"
"cargo:cargo-release" = "0.25.18"
"cargo:cargo-remark" = "0.1.2"
"cargo:cargo-script-mvs" = "0.2.0"
"cargo:cargo-semver-checks" = "0.41.0"
"cargo:cargo-show-asm" = "0.2.49"
"cargo:cargo-shuttle" = "0.54.0"
"cargo:cargo-test-fuzz" = "7.2.0"
"cargo:cargo-udeps" = "0.1.55"
"cargo:cargo-update" = "16.3.0"
"cargo:cargo-upgrades" = "2.2.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:create-tauri-app" = "4.5.10"
"cargo:cross" = "0.2.5"
"cargo:daktilo" = "0.6.0"
"cargo:dalance/procs" = "HEAD"
"cargo:deno" = "2.3.1"
"cargo:diesel_cli" = "2.2.10"
"cargo:diffsitter" = "0.9.0"
"cargo:diskonaut" = "0.11.0"
"cargo:du-dust" = "1.2.0"
"cargo:duf" = "0.19.0"
"cargo:efmt" = "0.19.1"
"cargo:evcxr_jupyter" = "0.19.0"
"cargo:evcxr_repl" = "0.19.0"
"cargo:fd-find" = "10.2.0"
"cargo:fend" = "1.5.6"
"cargo:flamegraph" = "0.6.8"
"cargo:fselect" = "0.8.11"
"cargo:fundoc" = "0.5.0"
"cargo:git-delta" = "0.18.2"
"cargo:gitui" = "0.27.0"
"cargo:grex" = "1.4.5"
"cargo:just" = "1.40.0"
"cargo:license-generator" = "1.3.0"
"cargo:lms" = "0.4.0"
"cargo:loco" = "0.15.0"
"cargo:lurk-cli" = "0.3.9"
"cargo:lychee" = "0.18.1"
"cargo:mdbook" = "0.4.49"
"cargo:mdbook-i18n-helpers" = "0.3.6"
"cargo:mdbook-katex" = "0.9.4"
"cargo:mdbook-svgbob" = "0.2.1"
"cargo:mdbook-toc" = "0.14.2"
"cargo:mdcat" = "2.7.1"
"cargo:miniserve" = "0.29.0"
"cargo:numbat-cli" = "1.16.0"
"cargo:pagefind" = "1.3.0"
"cargo:panamax" = "1.0.14"
"cargo:pngquant" = "3.0.3"
"cargo:proximity-sort" = "1.3.0"
"cargo:pueue" = "4.0.0"
"cargo:qcp" = "0.4.0"
"cargo:ripgrep" = "14.1.1"
"cargo:rless" = "0.0.5"
"cargo:rustlings" = "6.4.0"
"cargo:rustypaste" = "0.16.1"
"cargo:rustypaste-cli" = "0.9.4"
"cargo:rvim" = "0.0.8"
"cargo:sccache" = "0.10.0"
"cargo:sd" = "1.0.0"
"cargo:slumber" = "3.1.1"
"cargo:speedtest-rs" = "0.2.0"
"cargo:sqlx-cli" = "0.8.5"
"cargo:stdrename" = "1.3.0"
"cargo:taskwarrior-tui" = "0.26.3"
"cargo:tauri-cli" = "2.5.0"
"cargo:tealdeer" = "1.7.2"
"cargo:tickrs" = "0.14.11"
"cargo:tokei" = "12.1.2"
"cargo:trashy" = "2.0.0"
"cargo:trunk" = "0.21.14"
"cargo:typos-cli" = "1.32.0"
"cargo:typst-lsp" = "0.0.0"
"cargo:ugdb" = "0.1.12"
"cargo:wasmtime-cli" = "32.0.0"
"cargo:wiki-tui" = "0.9.1"
"cargo:workshop-runner" = "0.2.4"
"cargo:xsv" = "0.13.0"
"cargo:yazi-cli" = "25.4.8"
"cargo:yazi-fm" = "25.4.8"
"cargo:zet" = "2.0.1"
"cargo:zoxide" = "0.9.7"
chezmoi = "2.62.2"
cmake = "4.0.1"
coder = "2.22.0"
delta = "0.18.2"
direnv = "2.36.0"
docker-compose = "2.35.0"
doggo = "1.0.5"
dua = "2.30.0"
duckdb = "1.2.2"
duf = "0.8.1"
elixir = "1.18.3-otp-27"
erlang = "28"
fastfetch = "2.43.0"
fd = "10.2.0"
ffmpeg = "7.1.1"
flyctl = "0.3.115"
gcloud = "521.0.0"
github-cli = "2.72.0"
gleam = "1.10.0"
go = "1.24.2"
"go:github.com/pcarrier/gauth" = "1.5.0"
"go:golang.org/x/tools/gopls" = "0.18.1"
grex = "1.4.5"
gum = "0.16.0"
haskell = "9.10.1"
helix = "25.01.1"
helm = "3.17.3"
heroku = "9.5.1"
hexyl = "0.16.0"
httpie-go = "0.7.0"
hub = "2.14.2"
hyperfine = "1.19.0"
java = "24.0.1"
jc = "1.25.4"
jq = "1.7.1"
just = "1.40.0"
k9s = "0.50.4"
kubecm = "0.33.0"
kubectl = "1.33.0"
kubectx = "0.9.5"
kubens = "0.9.5"
kubent = "0.7.3"
kubie = "0.25.2"
lazydocker = "0.24.1"
linkerd = "edge-25.5.1"
llvm-objdump = "20.1.4"
lua = "5.4.7"
mdbook = "0.4.48"
mold = "2.39.0"
mysql = "8.0.33"
neovim = "0.11.1"
ninja = "1.12.1"
node = "24.0.0"
"npm:docco" = "0.9.2"
numbat = "1.16.0"
octosql = "0.13.0"
opam = "2.3.0"
opentofu = "1.9.1"
pandoc = "3.6.4"
pipx = "1.7.1"
"pipx:llm" = "0.25"
postgres = "17.4"
protoc = "25.7"
python = "3.13.3"
r = "4.5.0"
redis = "8.0.0"
rg = "14.1.1"
ruby = "3.4.3"
scala = "3.6.4"
sccache = "0.10.0"
sd = "1.0.0"
sqlite = "3.49.1"
typos = "1.32.0"
typst = "0.13.1"
yazi = "25.4.8"
yt-dlp = "2025.10.22"
zoxide = "0.9.7"
